server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  jwt:
    access_token:
      prifile: '/data/conf/rsa/private_key.pem'
      pubfile: '/data/conf/rsa/public_key.pem'
      expire_in: 3600
    refresh_token:
      prifile: '/data/conf/rsa/refresh_private_key.pem'
      pubfile: '/data/conf/rsa/refresh_public_key.pem'
      expire_in: 86400
  limit:
    daily_max_new_user_num: 100
    daily_max_new_msg_num: 5000
data:
  env: production
  database:
    driver: mysql
    source: root:123456@tcp(host.docker.internal:3306)/chatsvc?parseTime=True&loc=Local
  redis:
    addr: host.docker.internal:6379
    password: '123456'
    db: 0
