server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  jwt:
    access_token:
      prifile: 'configs/rsa/private_key.pem'
      pubfile: 'configs/rsa/public_key.pem'
      expire_in: 3600
    refresh_token:
      prifile: 'configs/rsa/refresh_private_key.pem'
      pubfile: 'configs/rsa/refresh_public_key.pem'
      expire_in: 86400
  limit:
    daily_max_new_user_num: 100
    daily_max_new_msg_num: 5000
data:
  env: dev
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/chatsvc?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    password: '123456'
    db: 0
