// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameConfig = "configs"

// Config 配置项
type Config struct {
	ID        int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ParentID  int32      `gorm:"column:parent_id;not null;comment:上级配置 id" json:"parent_id"` // 上级配置 id
	Key       string     `gorm:"column:key;not null;comment:配置名称" json:"key"`                // 配置名称
	Value     string     `gorm:"column:value;not null;comment:配置参数" json:"value"`            // 配置参数
	Comment   string     `gorm:"column:comment;not null;comment:备注" json:"comment"`          // 备注
	CreatedAt *time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`           // 创建时间
	UpdatedAt *time.Time `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`           // 更新时间
}

// TableName Config's table name
func (*Config) TableName() string {
	return TableNameConfig
}
