// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFriend = "friends"

// Friend 好友关系表
type Friend struct {
	ID              int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID          int32      `gorm:"column:user_id;not null;comment:用户id" json:"user_id"`                      // 用户id
	FriendID        int32      `gorm:"column:friend_id;not null;comment:好友id" json:"friend_id"`                  // 好友id
	FriendNickname  string     `gorm:"column:friend_nickname;not null;comment:昵称" json:"friend_nickname"`        // 昵称
	FriendAvatarURL string     `gorm:"column:friend_avatar_url;not null;comment:头像url" json:"friend_avatar_url"` // 头像url
	Remark          string     `gorm:"column:remark;not null;comment:备注" json:"remark"`                          // 备注
	CreatedAt       *time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                         // 创建时间
}

// TableName Friend's table name
func (*Friend) TableName() string {
	return TableNameFriend
}
