// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePrivateMessage = "private_messages"

// PrivateMessage 私聊消息表
type PrivateMessage struct {
	ID        int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SendID    int32      `gorm:"column:send_id;not null;comment:用户uid" json:"send_id"`                  // 用户uid
	RecvID    int32      `gorm:"column:recv_id;not null;comment:好友uid" json:"recv_id"`                  // 好友uid
	Content   string     `gorm:"column:content;not null;comment:发送内容" json:"content"`                   // 发送内容
	Type      int32      `gorm:"column:type;not null;comment:消息类型" json:"type"`                         // 消息类型
	Status    int32      `gorm:"column:status;not null;comment:状态 0:未送达 1:已送达 2:撤回 3:已读" json:"status"` // 状态 0:未送达 1:已送达 2:撤回 3:已读
	CreatedAt *time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                      // 创建时间
}

// TableName PrivateMessage's table name
func (*PrivateMessage) TableName() string {
	return TableNamePrivateMessage
}
