// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSensitiveWord = "sensitive_words"

// SensitiveWord 敏感词
type SensitiveWord struct {
	ID        int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Content   string     `gorm:"column:content;not null;comment:敏感词内容" json:"content"`        // 敏感词内容
	Enabled   int32      `gorm:"column:enabled;not null;comment:是否启用 1:是 0:否" json:"enabled"` // 是否启用 1:是 0:否
	CreatedAt *time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`            // 创建时间
	UpdatedAt *time.Time `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`            // 更新时间
}

// TableName SensitiveWord's table name
func (*SensitiveWord) TableName() string {
	return TableNameSensitiveWord
}
