name: Docker Image CI

on:
  push:
    branches: ['master']
    paths:
      - '**.md'
      - 'docs/**'

jobs:
  build-push:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Short SHA
        run: |
          echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ vars.REGISTRY }}/${{ vars.NAMESPACE }}/chatsvc:latest
            ${{ vars.REGISTRY }}/${{ vars.NAMESPACE }}/chatsvc:${{ env.SHORT_SHA }}
